/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PostRouteImport } from './routes/post'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as CreateListingRouteImport } from './routes/create-listing'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityIdRouteImport } from './routes/opportunity.$id'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateListingRoute = CreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/create-listing': typeof CreateListingRoute
  '/employer': typeof EmployerRoute
  '/explore': typeof ExploreRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/tracker': typeof TrackerRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/create-listing': typeof CreateListingRoute
  '/employer': typeof EmployerRoute
  '/explore': typeof ExploreRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/tracker': typeof TrackerRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/create-listing': typeof CreateListingRoute
  '/employer': typeof EmployerRoute
  '/explore': typeof ExploreRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/tracker': typeof TrackerRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/create-listing'
    | '/employer'
    | '/explore'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/saved'
    | '/tracker'
    | '/opportunity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/create-listing'
    | '/employer'
    | '/explore'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/saved'
    | '/tracker'
    | '/opportunity/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/create-listing'
    | '/employer'
    | '/explore'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/saved'
    | '/tracker'
    | '/opportunity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CreateListingRoute: typeof CreateListingRoute
  EmployerRoute: typeof EmployerRoute
  ExploreRoute: typeof ExploreRoute
  PostRoute: typeof PostRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  TrackerRoute: typeof TrackerRoute
  OpportunityIdRoute: typeof OpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-listing': {
      id: '/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof CreateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CreateListingRoute: CreateListingRoute,
  EmployerRoute: EmployerRoute,
  ExploreRoute: ExploreRoute,
  PostRoute: PostRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  TrackerRoute: TrackerRoute,
  OpportunityIdRoute: OpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
